---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGd6bWZkc3U2Cg==
  CLOUDINARY_KEY: NTMxMTUzNTQ4NzMzNzI4Cg==
  CLOUDINARY_SECRET: NFB3bEZaN0Y1WF9acW5tcE5IckIwOVFtN3BjCg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2llblZpWVdseWVtOXVaU0lzSW1FaU9pSmpiWEZoZVhWa1pqVXdZV2xqTW5GeGVYRm5ibXR6Y1RWd0luMC5uTlUxM0o4a2pkZUR4UTNUeW5YTmpBCg==
  DB_URL: bW9uZ29kYitzcnY6Ly9tZHh1YmFpcjYxNTJfZGJfdXNlcjpzSG01Q3l1NExCVHlOVFRKQHp1YmFpci1kcy5iYnkxdzFlLm1vbmdvZGIubmV0Lz9hcHBOYW1lPXp1YmFpci1kcwo=
  SECRET: enViYWlyCg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: zubairzone/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
